<a href="https://colab.research.google.com/github/vaishnavisable2005/workshop/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing numpy**

In [1]:
import numpy as np

# **Creating numpy arrays**

In [2]:
np.array
import numpy as np
a=np.array([1,2,3])
print(a)
a=np.array([1,2,3,4,5,6])
a

[1 2 3]


array([1, 2, 3, 4, 5, 6])

# 2D array: An array of arrays

In [3]:
#20 and 30
b=np.array([[2,3],[5,6]])
print(b)

[[2 3]
 [5 6]]


# 3D array: An array of 2D array

In [4]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#dtype
#np.array([1,2,3],dtype=float)
a=np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [6]:
np.array([1,2,3],dtype=np.uint8)
print(a)
print(a.dtype)

b=np.array([1,2,3],dtype=complex)
print(b)
print(b.dtype)

[1. 2. 3.]
float64
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [7]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
#with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [9]:
np.ones and np.zeros

<function numpy.zeros>

In [10]:
#np.random
np.random.random((3,4))

array([[0.64503744, 0.87851669, 0.9335082 , 0.17826928],
       [0.88952512, 0.55935299, 0.0071153 , 0.97687125],
       [0.10215921, 0.22332632, 0.49720129, 0.75477728]])

In [12]:
#np.linspace
np.linspace(-10,10,1000,dtype=float)

array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
        -9.91991992,  -9.8998999 ,  -9.87987988,  -9.85985986,
        -9.83983984,  -9.81981982,  -9.7997998 ,  -9.77977978,
        -9.75975976,  -9.73973974,  -9.71971972,  -9.6996997 ,
        -9.67967968,  -9.65965966,  -9.63963964,  -9.61961962,
        -9.5995996 ,  -9.57957958,  -9.55955956,  -9.53953954,
        -9.51951952,  -9.4994995 ,  -9.47947948,  -9.45945946,
        -9.43943944,  -9.41941942,  -9.3993994 ,  -9.37937938,
        -9.35935936,  -9.33933934,  -9.31931932,  -9.2992993 ,
        -9.27927928,  -9.25925926,  -9.23923924,  -9.21921922,
        -9.1991992 ,  -9.17917918,  -9.15915916,  -9.13913914,
        -9.11911912,  -9.0990991 ,  -9.07907908,  -9.05905906,
        -9.03903904,  -9.01901902,  -8.998999  ,  -8.97897898,
        -8.95895896,  -8.93893894,  -8.91891892,  -8.8988989 ,
        -8.87887888,  -8.85885886,  -8.83883884,  -8.81881882,
        -8.7987988 ,  -8.77877878,  -8.75875876,  -8.73

In [13]:
np.random.randint(2,10,5)

array([3, 2, 7, 2, 2])

In [14]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [15]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [18]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.size

[[1 2 3]
 [4 5 6]]


6

In [19]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.ndim

[[1 2 3]
 [4 5 6]]


2

In [20]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [21]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.itemsize

[[1 2 3]
 [4 5 6]]


8

In [22]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.nbytes

[[1 2 3]
 [4 5 6]]


48

In [23]:
a=np.arange(12)
a.ndim

1

In [24]:
#ndim
a3.ndim

3

In [25]:
a1.shape

(10,)

In [26]:
a2.shape

(3, 4)

In [27]:
a3.shape

(2, 2, 2)

# Changing Datatypes:
You can change the data type of a numpy array using the **.astype()** method.

In [28]:
a3.dtype

dtype('int64')

In [29]:
#astype
a3.astype(np.int32)
a3.astype(np.float32).dtype

dtype('float32')

# Array Operations

In [32]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
#scaler operations
#arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [34]:
#relational
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [35]:
#vector operation
#arithmetic
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [36]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[74., 10., 74.],
       [60., 29.,  8.],
       [57., 25.,  8.]])

In [37]:
#max/min/sum/np.prod
#0->col and 1 ->row
np.prod(a1,axis=0)

array([253080.,   7250.,   4736.])

In [38]:
#mean/median/std/var
np.sin(a1)

array([[-0.98514626, -0.54402111, -0.98514626],
       [-0.30481062, -0.66363388,  0.98935825],
       [ 0.43616476, -0.13235175,  0.98935825]])

In [40]:
#angle array in degrees
angles_deg=np.array([0,30,45,60,90])
#convert to radians
angles_rad=np.deg2rad(angles_deg)

print("angles in degree:",angles_deg)
print("angles in radian:",angles_rad)

print("sine:",np.sin(angles_rad))
print("cosine:",np.cos(angles_rad))
print("Tangent:",np.tan(angles_rad))


angles in degree: [ 0 30 45 60 90]
angles in radian: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sine: [0.         0.5        0.70710678 0.8660254  1.        ]
cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [43]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [44]:
#log and exponents
np.exp(a1)

array([[1.37338298e+32, 2.20264658e+04, 1.37338298e+32],
       [1.14200739e+26, 3.93133430e+12, 2.98095799e+03],
       [5.68572000e+24, 7.20048993e+10, 2.98095799e+03]])

In [45]:
#round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[68., 55., 51.],
       [93., 48.,  1.]])