<a href="https://colab.research.google.com/github/vaishnavisable2005/workshop/blob/main/Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Importing numpy**

In [3]:
import numpy as np

In [4]:
import numpy as np

# **Creating numpy arrays**

In [5]:
np.array
import numpy as np
a=np.array([1,2,3])
print(a)
a=np.array([1,2,3,4,5,6])
a

[1 2 3]


array([1, 2, 3, 4, 5, 6])

# 2D array: An array of arrays

In [6]:
#20 and 30
b=np.array([[2,3],[5,6]])
print(b)

[[2 3]
 [5 6]]


# 3D array: An array of 2D array

In [7]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#dtype
#np.array([1,2,3],dtype=float)
a=np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [9]:
np.array([1,2,3],dtype=np.uint8)
print(a)
print(a.dtype)

b=np.array([1,2,3],dtype=complex)
print(b)
print(b.dtype)

[1. 2. 3.]
float64
[1.+0.j 2.+0.j 3.+0.j]
complex128


In [10]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
#with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [12]:
np.ones and np.zeros

<function numpy.zeros>

In [13]:
#np.random
np.random.random((3,4))

array([[0.53121245, 0.86400531, 0.25523758, 0.22937002],
       [0.74660455, 0.56937585, 0.23203987, 0.36862551],
       [0.44295437, 0.23985631, 0.18359541, 0.2722552 ]])

In [14]:
#np.linspace
np.linspace(-10,10,1000,dtype=float)

array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
        -9.91991992,  -9.8998999 ,  -9.87987988,  -9.85985986,
        -9.83983984,  -9.81981982,  -9.7997998 ,  -9.77977978,
        -9.75975976,  -9.73973974,  -9.71971972,  -9.6996997 ,
        -9.67967968,  -9.65965966,  -9.63963964,  -9.61961962,
        -9.5995996 ,  -9.57957958,  -9.55955956,  -9.53953954,
        -9.51951952,  -9.4994995 ,  -9.47947948,  -9.45945946,
        -9.43943944,  -9.41941942,  -9.3993994 ,  -9.37937938,
        -9.35935936,  -9.33933934,  -9.31931932,  -9.2992993 ,
        -9.27927928,  -9.25925926,  -9.23923924,  -9.21921922,
        -9.1991992 ,  -9.17917918,  -9.15915916,  -9.13913914,
        -9.11911912,  -9.0990991 ,  -9.07907908,  -9.05905906,
        -9.03903904,  -9.01901902,  -8.998999  ,  -8.97897898,
        -8.95895896,  -8.93893894,  -8.91891892,  -8.8988989 ,
        -8.87887888,  -8.85885886,  -8.83883884,  -8.81881882,
        -8.7987988 ,  -8.77877878,  -8.75875876,  -8.73

In [15]:
np.random.randint(2,10,5)

array([6, 9, 2, 8, 6])

In [16]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [17]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [18]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [19]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.size

[[1 2 3]
 [4 5 6]]


6

In [20]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.ndim

[[1 2 3]
 [4 5 6]]


2

In [21]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.dtype

[[1 2 3]
 [4 5 6]]


dtype('int64')

In [22]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.itemsize

[[1 2 3]
 [4 5 6]]


8

In [23]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.nbytes

[[1 2 3]
 [4 5 6]]


48

In [24]:
a=np.arange(12)
a.ndim

1

In [25]:
#ndim
a3.ndim

3

In [26]:
a1.shape

(10,)

In [27]:
a2.shape

(3, 4)

In [28]:
a3.shape

(2, 2, 2)

# Changing Datatypes:
You can change the data type of a numpy array using the **.astype()** method.

In [29]:
a3.dtype

dtype('int64')

In [30]:
#astype
a3.astype(np.int32)
a3.astype(np.float32).dtype

dtype('float32')

# Array Operations

In [31]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
#scaler operations
#arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [33]:
#relational
a2==15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
#vector operation
#arithmetic
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [35]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[49., 28., 90.],
       [16., 68., 94.],
       [29.,  4., 82.]])

In [36]:
#max/min/sum/np.prod
#0->col and 1 ->row
np.prod(a1,axis=0)

array([ 22736.,   7616., 693720.])

In [37]:
#mean/median/std/var
np.sin(a1)

array([[-0.95375265,  0.27090579,  0.89399666],
       [-0.28790332, -0.89792768, -0.24525199],
       [-0.66363388, -0.7568025 ,  0.31322878]])

In [38]:
#angle array in degrees
angles_deg=np.array([0,30,45,60,90])
#convert to radians
angles_rad=np.deg2rad(angles_deg)

print("angles in degree:",angles_deg)
print("angles in radian:",angles_rad)

print("sine:",np.sin(angles_rad))
print("cosine:",np.cos(angles_rad))
print("Tangent:",np.tan(angles_rad))


angles in degree: [ 0 30 45 60 90]
angles in radian: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sine: [0.         0.5        0.70710678 0.8660254  1.        ]
cosine: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [39]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [40]:
#log and exponents
np.exp(a1)

array([[1.90734657e+21, 1.44625706e+12, 1.22040329e+39],
       [8.88611052e+06, 3.40427605e+29, 6.66317622e+40],
       [3.93133430e+12, 5.45981500e+01, 4.09399696e+35]])

In [41]:
#round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[ 4., 34., 12.],
       [79., 21., 54.]])

# Indexing and slicing

In [48]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [49]:
a1

array([[49., 28., 90.],
       [16., 68., 94.],
       [29.,  4., 82.]])

In [50]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2[1,0]

np.int64(4)

In [52]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [53]:
a3[1,0]

np.int64(15)

In [54]:
a3[1,1]

np.int64(16)

In [55]:
a1[2:5:2]

array([[29.,  4., 82.]])

In [56]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [58]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [61]:
a1
for i in a1:
  print(i)

[49. 28. 90.]
[16. 68. 94.]
[29.  4. 82.]


In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [64]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [66]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [67]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [68]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])